# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

# SET YOUR VARIABLES AND RENAME THIS FILE DO application.yml
DATABASE_URL: jdbc:mysql://localhost:3306
DATABASE_USERNAME: root
DATABASE_PASSWORD: root
HOTTOK: hotmart_token
SMTP_HOST: smtp.gmail.com
SMTP_PORT: 587
SMTP_SSL: false
SMTP_USERNAME: email@gmail.com
SMTP_PASSWORD: 123456
SMTP_TEST_TO: youremailtoreceive@gmail.com
BRAND_NAME: YourBrand
CRYPT_KEY: 12345678901234567890123456789012